variables:
    CC-AWS-ELEM_VPC_PRIVATESUBNET_RTNAME:
        required: false
        description: The private subnet route table
        default: cc-default_vpc-default_private_subnet-rt
    CC-AWS-ELEM_VPC_NAME:
        required: false
        description: The name of the VPC
        default: cc-default_vpc
    CC-AWS-ELEM_VPC_PRIVATESUBNET_NAME:
        required: false
        description: The private subnet
        default: cc-default_vpc-default_private_subnet
    CC-AWS-ELEM_VPC_PUBLICSUBNET_RTNAME:
        required: false
        description: The public subnet route table
        default: cc-default_vpc-default_public_subnet-rt
    CC-AWS-ELEM_VPC_PUBLICSUBNET_NAME:
        required: false
        description: The public subnet
        default: cc-default_vpc-default_public_subnet
    CC-AWS-ELEM_VPC_OCTETS:
        required: false
        description: The network for the VPC
        default: 10.0.0.0
    CC-AWS-ELEM_VPC_MASK:
        required: false
        description: The network mask for the VPC
        default: "16"
