variables:
    PRIVATESUBNET_RTNAME:
        required: false
        description: The private subnet route table
        default: cc-default_vpc-default_private_subnet-rt
    VPC_NAME:
        required: false
        description: The name of the VPC
        default: cc-default_vpc
    PRIVATESUBNET_NAME:
        required: false
        description: The private subnet
        default: cc-default_vpc-default_private_subnet
    PUBLICSUBNET_RTNAME:
        required: false
        description: The public subnet route table
        default: cc-default_vpc-default_public_subnet-rt
    PUBLICSUBNET_NAME:
        required: false
        description: The public subnet
        default: cc-default_vpc-default_public_subnet
    VPC_OCTETS:
        required: false
        description: The network for the VPC
        default: 10.1.0.0
    VPC_MASK:
        required: false
        description: The network mask for the VPC
        default: "16"
